FIX Update oembed config
silverstripe/cwp-core pull request #107
Opened 2022-05-11 01:54 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10305

2022-05-11 02:53 UTC, GuySartorelli commented
The fact that this is passing in travis when its dependencies aren't merged in yet seems a bit concerning... is there some tests that should be added to test this?

2022-05-11 04:22 UTC, emteknetnz commented
It's hard to test since what the purpose of this is to work on CWP hosting where there are some environment variable set.

I've added a unit test to test that framework is configured to create a Guzzle client, so in case we change the client again in the future so the config makes no sense, it should break.

2022-05-12 07:10 UTC, GuySartorelli commented
The tests which are set to use installer 4.10 are failing - this PR updates the dependency to 4.11 so we should update the test config.

2022-05-12 07:11 UTC, GuySartorelli requested changes
The tests are failing

2022-05-12 22:40 UTC, GuySartorelli approved these changes

2022-05-12 22:40 UTC, merged